// Generated by Grafana k6 Studio (1.11.0) on 2026-02-06T17:05:58.680Z

import { group, sleep, check } from "k6";
import http from "k6/http";
import execution from "k6/execution";

export const options = {
  stages: [
    { target: 1200, duration: "50s" },
    { target: 1200, duration: "2m" },
    { target: 0, duration: "30s" },
  ],
};

export default function () {
  let params;
  let resp;
  let match;
  let regex;
  let url;

  let randProduct;
  let randCategory;
  let randFirst;
  let second;

  const correlation_vars = {};

  group("Default group", function () {


    params = {
  headers: {
    accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`
  },
  tags: {
    name: 'GetProductRange'
  }
};

randCategory = Math.floor(Math.random() * (60 - 1 + 1) + 1);
randFirst = Math.floor(Math.random() * 84) * 20 + 1;
second = randFirst + 20;
url = `http://localhost:5232/api/Product/GetRange?categoryId=${randCategory}&firstProductNumber=${randFirst}&lastProductNumber=${second}`;

resp = http.request("GET", url, null, params);
    sleep(1);

    params = {
      headers: {
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`
      },
      tags: {
    name: 'GetCategoriesList'
  }
    };

    url = `http://localhost:5232/api/Category`;
    resp = http.request("GET", url, null, params);
    sleep(1);


    params = {
  headers: {
    accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`
  },
  tags: {
    name: 'GetProductRange'
  }
};

randCategory = Math.floor(Math.random() * (60 - 1 + 1) + 1);
randFirst = Math.floor(Math.random() * 84) * 20 + 1;
second = randFirst + 20;
url = `http://localhost:5232/api/Product/GetRange?categoryId=${randCategory}&firstProductNumber=${randFirst}&lastProductNumber=${second}`;

resp = http.request("GET", url, null, params);
    sleep(1);

    params = {
      headers: {
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
      },
      tags: {
    name: 'GetProduct'
  }
    };

    randProduct = Math.floor(Math.random() * (60000 - 1 + 1) + 1);
    url = `http://localhost:5232/api/Product/Get?id=${randProduct}`;
    resp = http.request("GET", url, null, params);
    sleep(1);

    params = {
  headers: {
    accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`
  },
  tags: {
    name: 'GetProductRange'
  }
};

randCategory = Math.floor(Math.random() * (60 - 1 + 1) + 1);
randFirst = Math.floor(Math.random() * 84) * 20 + 1;
second = randFirst + 20;
url = `http://localhost:5232/api/Product/GetRange?categoryId=${randCategory}&firstProductNumber=${randFirst}&lastProductNumber=${second}`;

resp = http.request("GET", url, null, params);
    sleep(1);

    params = {
      headers: {
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`
      },
      tags: {
    name: 'GetProduct'
  }
    };

    randProduct = Math.floor(Math.random() * (60000 - 1 + 1) + 1);
    url = `http://localhost:5232/api/Product/Get?id=${randProduct}`;
    resp = http.request("GET", url, null, params);
    sleep(1);
  });
  //sleep(1);
}
